name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: |
          pnpm install --frozen-lockfile
      - run: |
          pnpm all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          machinePath: __tests__/data/result.json
          coveragePath: __tests__/data/lcov.info
